# Project Information
site_name: Enter Key Hacker - ATT&CK Matrix
site_description: hacking just need the enter key
site_author: 00theway
site_url: https://github.com/Enter-hacker/ATT-CK


# Repository
repo_name: 'Enter-hacker/ATT-CK'
repo_url: 'https://github.com/Enter-hacker/ATT-CK'
edit_uri: 'edit/master/docs'


copyright: 'Copyright &copy; 2019 - 2020 Enter Key Team'

theme:
    name: 'material'
    language: 'zh'
    palette:
        primary: 'blue grey'
        accent: 'grey'
    logo: 'images/enter-key.svg'
    favicon: 'images/enter-key2.ico'
    feature:
        tabs: true
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'


nav:
    - ATT&CK Matrix:
        - Introduction: index.md
        - 入口打点:
            - 攻击策略TA0001: Tactics/TA0001.md
            - T1189(水坑攻击): TTPs/T1189.md
            - T1190(常规服务缺陷利用): TTPs/T1190.md
            - T1133(远程访问服务利用): TTPs/T1133.md
            - T1200(硬件外设接入攻击): TTPs/T1200.md
            - T1091(可插拔设备接入攻击): TTPs/T1091.md
            - T1193(钓鱼附件攻击): TTPs/T1193.md
            - T1192(钓鱼链接攻击): TTPs/T1192.md
            - T1194(第三方服务钓鱼攻击): TTPs/T1194.md
            - T1195(供应链攻击): TTPs/T1195.md
            - T1199(信任关系攻击): TTPs/T1199.md
            - T1078(凭据复用攻击): TTPs/T1078.md
        - 武器加载:
            - 攻击策略TA0002: Tactics/TA0002.md
            - T1155(AppleScript): TTPs/T1155.md
            - T1191(CMSTP): TTPs/T1191.md
            - T1059(命令行接口): TTPs/T1059.md
            - T1223(chm文件): TTPs/T1223.md
            - T1196(控制面板): TTPs/T1196.md
            - T1173(DDE): TTPs/T1173.md
            - T1106(系统API): TTPs/T1106.md
            - T1129(加载DLL): TTPs/T1129.md
            - T1203(应用程序溢出): TTPs/T1203.md
            - T1061(图形用户界面): TTPs/T1061.md
            - T1118(InstallUtil): TTPs/T1118.md
            - T1152(Launchctl): TTPs/T1152.md
            - T1168(linux系统计划任务): TTPs/T1168.md
            - T1177(LSASS Driver): TTPs/T1177.md
            - T1170(Mshta): TTPs/T1170.md
            - T1086(PowerShell): TTPs/T1086.md
            - T1121(Regsvcs/Regasm): TTPs/T1121.md
            - T1117(Regsvr32): TTPs/T1117.md
            - T1085(Rundll32): TTPs/T1085.md
            - T1053(windows系统计划任务): TTPs/T1053.md
            - T1064(脚本语言): TTPs/T1064.md
            - T1035(系统服务): TTPs/T1035.md
            - T1218(白名单程序利用): TTPs/T1218.md
            - T1216(白名单脚本利用): TTPs/T1216.md
            - T1153(Source): TTPs/T1153.md
            - T1151(长文件名隐藏后缀社工): TTPs/T1151.md
            - T1072(第三关管控程序): TTPs/T1072.md
            - T1154(Trap): TTPs/T1154.md
            - T1127(白名单开发工具): TTPs/T1127.md
            - T1204(社工欺骗用户运行程序): TTPs/T1204.md
            - T1047(WMI): TTPs/T1047.md
            - T1028(WinRM): TTPs/T1028.md
            - T1220(XSL脚本处理): TTPs/T1220.md
        - 持续控制:
            - 攻击策略TA0003: Tactics/TA0003.md
            - T1156(shell配置): TTPs/T1156.md 
            - T1015(远程访问系统特性): TTPs/T1015.md
            - T1182(AppCert DLLs): TTPs/T1182.md
            - T1103(AppInit DLLs): TTPs/T1103.md
            - T1118(InstallUtil): TTPs/T1118.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
        - 权限提升: 
            - 攻击策略TA0004: Tactics/TA0004.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
        - 纵向权限拓展:
            - 攻击策略TA0005: Tactics/TA0005.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
        - 凭据窃取:
            - 攻击策略TA0006: Tactics/TA0006.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
        - 网络空间测绘:
            - 攻击策略TA0007: Tactics/TA0007.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
        - 横向移动:
            - 攻击策略TA0008: Tactics/TA0008.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
        - 数据分析-信息收集:
            - 攻击策略TA0009: Tactics/TA0009.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
        - 远程控制:
            - 攻击策略TA0011: Tactics/TA0011.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
        - 数据窃取:
            - 攻击策略TA0010: Tactics/TA0010.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
        - 打扫战场:
            - 攻击策略TA0040: Tactics/TA0040.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
            - T0000(xxxx): TTPs/T0000.md
    - 缓解措施:
        - M1042(): Mitigations/M1042.md
    - 检测方法:
        - D-T1042(): Detection/D-T0000.md
    - 知识点集合:
        - Introduction: Knowledge.md
        - web:
            - KL0001(SQL语句): Knowledge/K0001.md
